apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: consoleapp-pdb
spec:
  minAvailable: 1  # Minimum number of pods that must remain available during voluntary disruptions
  selector:
    matchLabels:
      app: consoleapp